version: '3.9'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3001:3001"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/week06_lab
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:1
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=  
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
